apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rules
  labels:
    app.kubernetes.io/part-of: sre-challenge
    app.kubernetes.io/component: monitor-tools
data:
{{- range $path, $bytes := .Files.Glob "rules/*.yaml" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
