apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app.kubernetes.io/part-of: sre-challenge
    app.kubernetes.io/component: monitor-tools
type: Opaque
stringData:
  username: {{ .Values.grafana.user | quote }}
  password: {{ .Values.grafana.password | quote }}
