{
 "title": "SRE JVM overview",
 "tags": [
  "java",
  "jvm",
  "sre-challenge",
  "spring-boot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(jvm_memory_used{job=~\"sre-.*\", namespace=\"sre-challenge\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Memory used(heap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  sum without (id) (jvm_memory_used{area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  sum without (id) (jvm_memory_max{area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    }
   ]
  },
  {
   "title": "Memory used(nonheap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  sum without (id) (jvm_memory_used{area=\"nonheap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  sum without (id) (jvm_memory_max{area=\"nonheap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_threads_live{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "stat",
   "description": "The number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_classes_loaded{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Classes loaded"
    }
   ]
  },
  { "title": "Process overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Process start time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_start_time_seconds{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} * 1000\n)",
     "legendFormat": "{{instance}}: Process start time"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "Load average (avg): System's load average.  \n\nCPU count (avg): System's CPU count available to the process observed.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  system_load_average_1m{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Load average"
    },
    {
     "expr": "avg by (job,instance) (\n  system_cpu_count{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: CPU count"
    }
   ]
  },
  {
   "title": "CPU usage (process)",
   "type": "timeseries",
   "description": "CPU usage (process) (avg): Process CPU usage.  \n\nCPU usage (system) (avg): CPU Usage of host system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_cpu_usage{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (process)"
    },
    {
     "expr": "avg by (job,instance) (\n  system_cpu_usage{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (system)"
    }
   ]
  },
  {
   "title": "Process memory used (rss)",
   "type": "timeseries",
   "description": "Process resident memory size in bytes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_resident_memory_bytes{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process memory used (rss)"
    }
   ]
  },
  {
   "title": "Process files open",
   "type": "timeseries",
   "description": "Process files open (avg): Process files opened.  \n\nProcess files max (avg): Process files opened limit.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_files_open_files{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files open"
    },
    {
     "expr": "avg by (job,instance) (\n  process_files_max_files{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files max"
    }
   ]
  },
  { "title": "JVM memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "JVM memory used(heap)",
   "type": "timeseries",
   "description": "JVM memory used(heap) (avg): The used space is the amount of memory that is currently occupied by Java objects.  \n\nJVM memory max(heap) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nJVM memory committed(heap) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_used{area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_max{area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(heap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_committed{area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(heap)"
    }
   ]
  },
  {
   "title": "JVM memory used(nonheap)",
   "type": "timeseries",
   "description": "JVM memory used(nonheap) (avg): The amount of memory that is currently in non-heap.  \n\nJVM memory max(nonheap) (avg): Measure of memory max possible (non-heap). Returns -1 if the maximum memory size is undefined.  \n\nJVM memory committed(nonheap) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine(non-heap).\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_used{area=\"nonheap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_max{area=\"nonheap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_committed{area=\"nonheap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(nonheap)"
    }
   ]
  },
  { "title": "JVM garbage collection", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Eden Space (used)",
   "type": "timeseries",
   "description": "Eden Space (used) (avg): Memory used for G1 Eden Space Collection.  \n\nEden Space (max) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nEden Space (committed) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_used_bytes{id=~\"(G1 |PS )?Eden Space\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_max{id=~\"(G1 )?Eden Space\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)\n != -1",
     "legendFormat": "{{job}}: Eden Space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed{id=~\"(G1 |PS )?Eden Space\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (committed)"
    }
   ]
  },
  {
   "title": "Survival space (used)",
   "type": "timeseries",
   "description": "Survival space (used) (avg): Memory used for Survival collection.  \n\nSurvival space (max) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nSurvival space (committed) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_used{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (used)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_max{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"} != -1\n)",
     "legendFormat": "{{job}}: Survival space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (committed)"
    }
   ]
  },
  {
   "title": "Tenured space (used)",
   "type": "timeseries",
   "description": "Tenured space (used) (avg): Memory used for Tenured(Old Gen) collection.  \n\nTenured space (max) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nTenured space (committed) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_used{id=\"Tenured Gen\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_max{id=\"Tenured Gen\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)\n != -1",
     "legendFormat": "{{job}}: Tenured space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed{id=\"Tenured Gen\", area=\"heap\", job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (committed)"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  avg by (job,action,cause) (\n  rate(jvm_gc_pause_count{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "description": "GC time (avg) (avg): Garbage collection time (max).  \n\nGC time (max) (avg): Garbage collection time (max).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n  avg by (job, action, cause) (\n  rate(jvm_gc_pause_sum{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n  /\n  rate(jvm_gc_pause_count{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{job}}: {{ action }} ({{ cause }}) (avg)"
    },
    {
     "expr": "label_replace(\n  avg by (action,cause, job) (rate(jvm_gc_pause_max{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{job}}: {{ action }} ({{ cause }}) (max)"
    }
   ]
  },
  {
   "title": "Allocated/promoted",
   "type": "timeseries",
   "description": "Allocated (bytes) (avg): Memory allocated to Eden Space.  \n\nPromoted (avg): Memory promoted to Tenured Space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  rate(jvm_gc_memory_allocated{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Allocated (bytes)"
    },
    {
     "expr": "avg by (job) (\n  rate(jvm_gc_memory_promoted{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Promoted"
    }
   ]
  },
  { "title": "JVM threads", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Threads (avg): The current number of live threads including both daemon and non-daemon threads.  \n\nThreads (daemon) (avg): Daemon thread count of a JVM.  \n\nThreads (peak) (avg): Peak thread count of a JVM.  \n\nThreads (deadlocked) (avg): Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_threads_live{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_daemon{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (daemon)"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_peak{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (peak)"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_deadlocked{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (deadlocked)"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "timeseries",
   "description": "Threads by current state.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state, job) (jvm_threads_states{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "JVM buffers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 53 } },
  {
   "title": "Direct buffer used bytes",
   "type": "timeseries",
   "description": "Direct buffer used bytes (avg): Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.  \n\nDirect buffer capacity (avg): Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_memory_used{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer used bytes"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_total_capacity{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer capacity"
    }
   ]
  },
  {
   "title": "Mapped buffer used",
   "type": "timeseries",
   "description": "Mapped buffer used (avg): The mapped buffer pool is used for its FileChannel instances.  \n\nMapped buffer capacity (avg): The mapped buffer pool is used for its FileChannel instances.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_memory_used{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer used"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_total_capacity{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer capacity"
    }
   ]
  },
  {
   "title": "Hikari pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "stat",
     "description": "Hikari pool connections",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{job}}: Connections ({{pool}})"
      }
     ]
    },
    {
     "title": "Connections timeouts",
     "type": "stat",
     "description": "Hikari pool timeouts",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,pool) (\n  rate(hikaricp_connections_timeout_total{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{job}}: Connections timeouts ({{pool}})"
      }
     ]
    },
    {
     "title": "Connections (active) ",
     "type": "timeseries",
     "description": "Connections (active)  (avg): Hikari pool active connections.  \n\nConnections (idle)  (avg): Hikari pool idle connections.  \n\nConnections (pending)  (avg): Hikari pool pending connections.",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections_active{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{job}}: Connections (active)  ({{pool}})"
      },
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections_idle{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{job}}: Connections (idle)  ({{pool}})"
      },
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections_pending{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{job}}: Connections (pending)  ({{pool}})"
      }
     ]
    },
    {
     "title": "Connection create duration",
     "type": "timeseries",
     "description": "Connections creation time (avg) (avg): Hikari pool connection creation time.  \n",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_sum{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n/rate(hikaricp_connections_creation_count{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
       "legendFormat": "{{job}}: Connections creation time (avg) ({{pool}})"
      }
     ]
    },
    {
     "title": "Connection create duration",
     "type": "timeseries",
     "description": "Connections usage time (avg) (avg): Hikari pool connection usage time.  \n",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_sum{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n/rate(hikaricp_connections_usage_count{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
       "legendFormat": "{{job}}: Connections usage time (avg) ({{pool}})"
      }
     ]
    },
    {
     "title": "Connection acquire duration",
     "type": "timeseries",
     "description": "Connections acquire time (avg) (avg): Hikari pool connection acquire time.  \n",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_sum{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n/rate(hikaricp_connections_acquire_count{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
       "legendFormat": "{{job}}: Connections acquire time (avg) ({{pool}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logback events",
     "type": "timeseries",
     "description": "Logback events.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10,\n  sum by (job,level) (\n  rate(logback_events{job=~\"sre-.*\", namespace=\"sre-challenge\",job=~\"$job\",instance=~\"$instance\"}\n[$__rate_interval])\n)\n)",
       "legendFormat": "{{job}}: Logback events ({{level}})"
      }
     ]
    }
   ]
  }
 ]
}